### ISSUE TITLE
Fare menu

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#1]

**Comment by sisay82** [comment]
You have to implement the theming functionality in the CSS, if I change the theme off all the app it will not change in the menu, 

About the fonts use the golbal variables definitions when you will move on the SASS version.

**Comment by sisay82** [comment]
The menu array must be configurable from outside the component, the component must be much as possible configurable and data independent to reusability requirment.

**Comment by loribonna** [comment]
Just updated the branch with the corrections to the issues above. 

The array has an interface under shared/interfaces and is assigned from outside the component.
The CSS theme is assigned from the global styles.

**Comment by Bonny91** [comment]
Versione mobile: clicco su una voce, mi apre la pagina richiesta e il menu si chiude immediatamente (ora rimane aperto e devi ricliccare sull'icona perché si chiuda).
