### ISSUE TITLE
Non riesco più ad accedere nella mia homepage

### ISSUE THREAD

**Issue by LeleNacca** [sisay82/RifugiCAI#105]
Ho creato il mio account Firefly. Dopo qualche giorno ho trasferito dei MIOTA da un altro wallet e dopo aver fatto questo passaggio non riesco più ad accedere all'interno della mia homepage Firefly. Ho provato a disinstallare l'app e reinstallarla ma il problema permane.
Con il pc di un amico sono riuscito ad entrarci e ho verificato che le MI sono state trasferite correttamente quindi è sicuramente un problema del mio pc. Chiedo aiuto...

**Comment by loribonna** [comment]
Ti suggerisco di chiedere al supporto Firefly o in siti opportuni. Questa repo non ha nessun collegamento con Firefly o MIOTA e non e' un blog di supporto.
