### ISSUE TITLE
Fare bottoni

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#2]

**Comment by Bonny91** [comment]
Sulla pagina già esistente:
1)	Le scritte dei bottoni vanno sostituite con “Lista” e “Mappa”;
2)	L’icona della Map Marker è: <i class="fa fa-map-marker" aria-hidden="true"></i>
3)	Attenzione che nella versione mobile o quando si riduce lo schermo, questi diventano uno sopra l’altro: va tolto il testo e lasciate le icone nella stessa riga.


Altri bottoni presenti nell'applicativo:
- Salva e annulla modifiche.

**Comment by loribonna** [comment]
Created button component in core with support for mobile devices on branch "buttons".

Changed button links (map view, list view) to bc-buttons.
Created IButton interface in shared/interfaces.

Solved minor glitches:
- "List View" is now "Lista"
- "Map View" is now "Mappa"
- Buttons "Lista" and "Mappa" doesn't go one above the other.
- Changed icon "Mappa".

**Comment by Bonny91** [comment]
1) Per uniformare quanto è stato fatto da Michele nella lista e nell'utilizzo dei bottoni + e -, quando si passa col mouse sopra i bottoni, questi diventano grigi (vedi theming services, proprietà background hoover, fatta da Michele). La scritta va bene dell'accent color, ma anche il bordo del bottone Adesso il bordo diventa azzurro solo se clicco sul bottone per qualche secondo in più.
2) I bottoni "mappa" e "Lista", se visualizzati dal cellulare, vanno sopra la barra di ricerca.
3) Se si clicca sul map marker, il riquadro è piuttosto lontano. Andrebbe messo più vicino.

**Comment by Bonny91** [comment]
- Bottoni list e map view: nella versione mobile dell'home page (lista), attenzione: si spostano a destra; anche nella versionea  desktop sono a destra.
- Bottone menu: va di fianco a quello "torna indietro" nella pagina del rifugio, con la seguente sequenza: menu - torna indietro.
