### ISSUE TITLE
Bugfix lista rifugi

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#3]

**Comment by Bonny91** [comment]
1)	Ridurre l’altezza delle righe;
2)	I dati da visualizzare sono: Nome, Località, Sezione, Gruppo Regionale (devo chiarire con Sala che cosa intende). Il nome è sempre in grassetto.
3)	Quando si ricerca qualcosa, è evidenziato in grassetto la parola ricercata.
4)	Quando si passa il mouse su una riga, questa si evidenza dell’accent color. 
5)	Quando si seleziona una riga, questa si evidenza dell’accent color.
6)	La barra del copyright dev’essere 792x40 e la grandezza del font 12, non grassetto.

**Comment by Bonny91** [comment]
Bug: cliccando su un elemento della lista, questa si illumina interamente dell'accent color.

**Comment by sisay82** [comment]
1. The height of the rows is variable on the content. You can shrink the list Items from the normal size applying  the attribute dense on the element bc-list.
2. this is not a bug is a data change in the view. This doesn't affect the list component. 
3. The hover effect is gray  to have different feeling on it (when you pass on the row)
4.  the selected row is shown as active with the accent color
