### ISSUE TITLE
Ultime modifiche

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#39]
- Eliminare ovunque le **checkbox**;
- **Informazioni aggiuntive** e **servizi** non dovranno essere più dei tag;

- **Contatti**: 
a) il titolo della sezione (anche nella modalità modifica) dovrà essere "Contatti del rifugio";
b) telefono e cellulare: prevedere il +39 come prefisso internazionale, se si può.

- **Apertura**:
a) data di inizio e data di fine, formato dd/mm (senza yyyy).

- **Proprietà**:
a) telefono: prevedere il +39 come prefisso internazionale, se si può.
b) dopo la voce telefono, va inserito un nuovo campo: "Riferimento", con testo libero.
c) "Ritiro chiavi" e "Autogestione" vanno nella sezione "Custodia"

- **Custodia**:
a) telefono e cellulare: prevedere il +39 come prefisso internazionale, se si può.

**Comment by sisay82** [comment]
- Dati geografici: il titolo della sezione diventa "Dati geografici".
- Servizi: nella modalità modifiche normalizzare la distanza tra chiave e valore.
- Custodia: Ritiro chiavi e autogestione vanno sotto gli altri dati, non sopra tutti.

**Comment by Bonny91** [comment]
- Sezione "**Custode**", il cellulare se inserisco il +39 e +49 mi dice invalid --> Verificare che tutti i numeri di telefono presenti (quindi nella sezione contatti, proprietà e custodia) ammettano il + (che sia +39, +49, +43, +41 e +33). Sia nei telefoni sia nei cellulari.
- Non salva nella sezione "**proprietà e custodia**" + nella data di inizio e fine contratto, con la modalità modifica, ci viene scritto di default "invalid data".
- "Ritiro chiavi" e "Autogestione", nella modalità visualizzazione, sono separati dalla sezione della custodia con una riga, che va eliminata.
- Verificare che passando dalle sezioni legate ai dati (dati geografici ecc) a Documenti e Immagini, non ti cancelli i dati se non clicchi su salva!

**Comment by Bonny91** [comment]
Contatti del rifugio, aperture, proprietà e custodia= togliere i due punti nei titoli (mi erano sfuggitiiiiii)
Non so perché, ma se modifico la parte proprietà e custodia, ancora non salva. (ma invalid data non ci viene più scritto). Ad esempio= provo a inserire la data di inizio e di fine contratto sia nella proprietà sia nella custodia; se salvo, non salva. Invece, se inserisco la data di inizio e fine solo nella proprietà, allora salva. Se la inserisco solo nella custodia, invece, non salva, quindi potrebbe esserci un problema nella sezione custodia.
- ok per la riga che non c'è più (autogestione e ritiro chiavi), ma c'è ancora un po' troppo spazio =)
