### ISSUE TITLE
Sistema di login

### ISSUE THREAD

**Issue by sisay82** [sisay82/RifugiCAI#40]

**Comment by Bonny91** [comment]
- L'utente sezione NON modifica la maschera fissa; questa azione la fa solo l'utente centrale
- Effettuo il login con un utente sezione, clicco su un rifugio e poi su modifica --> tutti i campi appaiono vuoti
** Ricapitolando **
- Utente centrale --> visualizza tutto; modifica tutto; modifica la maschera fissa; aggiunge tutto; elimina tutto.
- Utente regione --> visualizza i rifugi DI PROPRIETÀ' della sua regione (non semplicemente localizzati nella sua Regione). No modifiche, no aggiunta e no eliminazione.
- Utente sezione --> visualizza rifugi della sua sezione; modifica tutto dei rifugi della sua sezione TRANNE la maschera fissa; non aggiunge e non elimina.

** Posizione cifre ID **
- Prima e seconda --> proprietà --> 93 sede centrale; 92 sezione.
- Terza e quarta --> Regione
- Quinta, sesta e settima posizione --> Tipo sezione

**Comment by Bonny91** [comment]
Se sono loggata col solito utente e invece della lista clicco su mappa, mi appaiono tutti i rifugi. Anche la mappa deve filtrare come la lista... soprattutto perché se clicco sopra un rifugio della mappa me lo fa aprire anche l'utente non ha i permessi per farlo!!

**Comment by Bonny91** [comment]
Se accedo con l'utente prova PresidenteGR, riesco a visualizzare la lista, ma non ad accedere ai rifugi. Cliccando su un rifugio, si carica per qualche secondo la scheda e poi vengo reindirizzata all'homepage con la lista.
