### ISSUE TITLE
Sezione Fruizione

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#51]
- Per i campi esistenti: vedi excel "Dati nel database", foglio "Fruizione".
- Per interfaccia: p 39 doc "Specifiche interfaccia CAI"

**Comment by loribonna** [comment]
- Normalizzare bottone a dimensioni di list view e map view.
- Allineare dati nelle colonne. Ridurre spaziatura tra le colonne.
-  Sistemare titoli nella modalità modifica. Eliminare spaziatura in modalità modifica.
