### ISSUE TITLE
Problemi di salvataggio e altro

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#63]
**Aggiungi rifugio**:
- _Maschera fissa_: togliere "Undefined" dai campi obbligatori;
- Messaggi di errore nei campi obbligatori della maschera fissa:
Nome: "Campo obbligatorio";
ID: "Campo obbligatorio; inserire solo numeri";
Sezione CAI: "Campo obbligatorio";
Proprietà: "Campo obbligatorio".
- Attenzione ai campi obbligatori che non li salva bene.

**Modifica rifugio**:
- _Servizi_: quando inserisco una voce, ogni parola ha la maiuscola; mettere la maiuscola solo all'inizio, oppure ai nomi propri (se si riesce).
- _Aperture_: Allineare la dicitura del campo e la voce.
- _Proprietà e custodia_: quando aggiungo un custode, le voci "autogestione" e "ritiro chiavi" si spostano da sotto "Proprietà" a sotto "Custode". Devono rimanere sotto "Proprietà", anche nella visualizzazione.  
Nella sezione "Custodia" non vengono fuori i msg di errore nei campi "Telefono" e "Cellulare". 
- _Documentazione amministrativa_: cambiare il messaggio d'errore in :"Caricare documento rinominato in "Tipo-fornitore-numero-data". Quando ci vengono scritti degli errori, le voci della sezione documentazione amministrativa (Imponibili ecc.) si posizionano su righe non allineate; vanno allineate.
- _Fruizione_: mettere in grassetto la riga "Soci" ecc. e la riga "Pernottamenti" ecc.. 

**Salvataggio**:
- Se inserisco un campo sbagliato, salvare tutto fuorché il campo che ho sbagliato e non l'intera sezione.

**Comment by loribonna** [comment]
Moved save issue to to #64 as Enhancement
