### ISSUE TITLE
1- Modifiche campi

### ISSUE THREAD

**Issue by Bonny91** [sisay82/RifugiCAI#80]
Maschera fissa:
•	“Tipo”: aggiungere voce “Ricoveri di emergenza”.
•	Aggiungere nuovo campo: “Stato”: “Immobile non agibile”, “In ristrutturazione”, "Momentaneamente chiuso”, “In attività” - PLACEHOLDER "Seleziona stato struttura".
•	Aggiungere "Aggiornato da" dopo "Aggiornato il": chi ha aggiornato il rifugio: sezione o sede centrale.
Dati geografici:
-	"Sito": far diventare la riga un rettangolo di 4 righe.

**Comment by loribonna** [comment]
Modifiche aggiunte su [Heroku ](http://app-cai.herokuapp.com/list)
